// lightarchitects-webshell-ui/src/components/CommandPalette.svelte
<script lang="ts">
  import { commandPaletteOpen } from '$lib/stores';
  import { SLASH_COMMANDS, parseCommand } from '$lib/commands';

  let query = $state('');
  let selectedIndex = $state(0);

  let filteredCommands = $derived(query
    ? SLASH_COMMANDS.filter(c =>
        c.name.includes(query.toLowerCase()) ||
        c.description.toLowerCase().includes(query.toLowerCase())
      )
    : SLASH_COMMANDS);

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape') {
      commandPaletteOpen.set(false);
      query = '';
    } else if (e.key === 'ArrowDown') {
      e.preventDefault();
      selectedIndex = Math.min(selectedIndex + 1, filteredCommands.length - 1);
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      selectedIndex = Math.max(selectedIndex - 1, 0);
    } else if (e.key === 'Enter' && filteredCommands[selectedIndex]) {
      filteredCommands[selectedIndex].execute(query);
      commandPaletteOpen.set(false);
      query = '';
    }
  }

  $effect(() => {
    function onKeydown(e: KeyboardEvent) {
      if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
        e.preventDefault();
        commandPaletteOpen.update(v => !v);
        query = '';
      } else if (e.key === 'Escape') {
        commandPaletteOpen.set(false);
        query = '';
      }
    }
    window.addEventListener('keydown', onKeydown, { capture: true });
    return () => window.removeEventListener('keydown', onKeydown, { capture: true });
  });
</script>

{#if $commandPaletteOpen}
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div
    class="fixed inset-0 z-[60] flex items-start justify-center pt-[20vh]"
    onclick={() => { commandPaletteOpen.set(false); query = ''; }}
    onkeydown={handleKeydown}
  >
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div
      class="w-[560px] max-w-[calc(100vw-2rem)] bg-[#0f1117] border border-[#1e293b] rounded-lg shadow-2xl overflow-hidden"
      onclick={(e) => e.stopPropagation()}
      onkeydown={(e) => e.stopPropagation()}
    >
      <div class="flex items-center px-4 py-3 border-b border-[#1e293b]">
        <span class="text-[#64748b] mr-2">/</span>
        <input
          type="text"
          bind:value={query}
          placeholder="Type a command…"
          class="flex-1 bg-transparent text-[#e2e8f0] outline-none text-sm font-mono"
        />
        <kbd class="text-[10px] text-[#475569] border border-[#334155] rounded px-1.5 py-0.5 ml-2">ESC</kbd>
      </div>
      <div class="max-h-[320px] overflow-y-auto">
        {#each filteredCommands as cmd, i}
          <button
            class="w-full flex items-center gap-3 px-4 py-2.5 text-left hover:bg-[#1e293b] {i === selectedIndex ? 'bg-[#1e293b]' : ''}"
            onclick={() => { cmd.execute(query); commandPaletteOpen.set(false); query = ''; }}
            onmouseenter={() => { selectedIndex = i; }}
          >
            <span class="text-[#94a3b8] font-mono text-sm">/{cmd.name}</span>
            <span class="text-[#475569] text-xs flex-1">{cmd.description}</span>
          </button>
        {/each}
      </div>
    </div>
  </div>
{/if}

// lightarchitects-webshell/web-figma/src/engineering/palette/CommandPalette.tsx
// ============================================================================
// File: web-figma/src/engineering/palette/CommandPalette.tsx
// Territory: ENGINEERING — not Figma Make synced
// Purpose: Cmd-K command palette stub (Phase 5 adds full command set)
// Security: commands are a static whitelist — no dynamic eval
// ============================================================================

import React, { useEffect, useState } from 'react';
import { Command } from 'cmdk';
import { useWebshellData } from '../store/EngineeringProvider';
import { SIBLINGS } from '../store/sceneState';

const SAFE_COMMANDS = ['focus', 'query', 'clear', 'pty restart'] as const;

function isSafeCommand(cmd: string): boolean {
  const lower = cmd.toLowerCase().trim();
  return SAFE_COMMANDS.some((safe) => lower === safe || lower.startsWith(`${safe} `));
}

export function CommandPalette() {
  const [open, setOpen] = useState(false);
  const [value, setValue] = useState('');
  const { setFocusedSibling } = useWebshellData();

  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
        e.preventDefault();
        setOpen((o) => !o);
      }
    }
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, []);

  if (!open) return null;

  function execute(cmd: string) {
    if (!isSafeCommand(cmd)) return;
    const [verb, arg] = cmd.toLowerCase().trim().split(' ');
    if (verb === 'focus' && arg && SIBLINGS.includes(arg as never)) {
      setFocusedSibling(arg);
    } else if (verb === 'focus' && !arg) {
      setFocusedSibling(null);
    }
    setValue('');
    setOpen(false);
  }

  return (
    <div style={{ position: 'fixed', inset: 0, zIndex: 100, display: 'flex', alignItems: 'flex-start', justifyContent: 'center', paddingTop: 80, background: 'rgba(0,0,0,0.4)' }} onClick={() => setOpen(false)}>
      <div style={{ width: 480, background: '#0a0a0f', border: '1px solid #1e293b', borderRadius: 8, overflow: 'hidden' }} onClick={(e) => e.stopPropagation()}>
        <Command>
          <Command.Input
            value={value}
            onValueChange={setValue}
            placeholder="Type a command…"
            onKeyDown={(e) => { if (e.key === 'Enter') execute(value); if (e.key === 'Escape') setOpen(false); }}
            style={{ width: '100%', padding: '12px 16px', background: 'transparent', border: 'none', outline: 'none', color: '#e2e8f0', fontFamily: "'JetBrains Mono', monospace", fontSize: 14 }}
          />
          <Command.List style={{ padding: 8 }}>
            {SIBLINGS.map((s) => (
              <Command.Item key={s} value={`focus ${s}`} onSelect={() => execute(`focus ${s}`)} style={{ padding: '6px 12px', borderRadius: 4, cursor: 'pointer', color: '#94a3b8', fontFamily: "'JetBrains Mono', monospace", fontSize: 12 }}>
                focus {s}
              </Command.Item>
            ))}
          </Command.List>
        </Command>
      </div>
    </div>
  );
}
